# Generated by Django 4.1.7 on 2023-03-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_price'),
        ('reservations', '0002_alter_reservation_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='properties.property'),
        ),
    ]
